// <auto-generated />
using System;
using Clinic_System.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic_System.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225200952_UpdatePayment")]
    partial class UpdatePayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AppointmentDateTime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AppointmentStatus");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate")
                        .HasDatabaseName("IX_Appointments_AppointmentDate");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Appointments_CreatedAt");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Appointments_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointments_Status");

                    b.HasIndex("AppointmentDate", "Status")
                        .HasDatabaseName("IX_Appointments_Date_Status");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("IX_Appointments_Doctor_Date");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DoctorName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specialization");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Doctors_ApplicationUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Doctors_CreatedAt");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("IX_Doctors_Specialization");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Nile Street, Cairo",
                            ApplicationUserId = "user-doc1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmed Mohamed",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345671",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Address = "28 Mohandessin, Giza",
                            ApplicationUserId = "user-doc2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sara Ali",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201012345672",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Address = "42 Nasr City, Cairo",
                            ApplicationUserId = "user-doc3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mohamed Hassan",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345673",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 4,
                            Address = "88 Zamalek, Cairo",
                            ApplicationUserId = "user-doc4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1982, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Layla Ibrahim",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201012345674",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 5,
                            Address = "55 Heliopolis, Cairo",
                            ApplicationUserId = "user-doc5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khaled",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345675",
                            Specialization = "Neurology"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DescriptionOfTheVisit")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("VisitDescription");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Diagnosis");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_MedicalRecords_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MedicalRecords_CreatedAt");

                    b.ToTable("MedicalRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "ينصح بتقليل الملح وممارسة الرياضة بانتظام",
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "المريض يعاني من ارتفاع في ضغط الدم، تم قياس الضغط وكان 150/95",
                            Diagnosis = "Hypertension",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "الراحة والإكثار من السوائل الدافئة",
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفل يعاني من كحة شديدة وحرارة، تم الفحص السريري",
                            Diagnosis = "Acute Bronchitis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "العلاج الطبيعي مرتين أسبوعياً وتجنب حمل الأثقال",
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "ألم في الركبة اليمنى، تم عمل أشعة وظهر احتكاك بسيط",
                            Diagnosis = "Knee Osteoarthritis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "تجنب الصابون القوي واستخدام المرطبات",
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفح جلدي في اليدين والرقبة، حكة شديدة",
                            Diagnosis = "Eczema",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "تجنب المحفزات مثل القهوة والتوتر",
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "صداع نصفي متكرر مع حساسية للضوء والصوت",
                            Diagnosis = "Migraine",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "الراحة وشرب السوائل الساخنة",
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "رشح وعطس واحتقان في الأنف منذ يومين",
                            Diagnosis = "Common Cold",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PatientName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_ApplicationUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Patients_CreatedAt");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Garden City, Cairo",
                            ApplicationUserId = "user-pat1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mahmoud Ali",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765431"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Dokki, Giza",
                            ApplicationUserId = "user-pat2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fatima Hassan",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "35 Zamalek, Cairo",
                            ApplicationUserId = "user-pat3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khalid",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765433"
                        },
                        new
                        {
                            Id = 4,
                            Address = "48 Agouza, Giza",
                            ApplicationUserId = "user-pat4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nour Mohamed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765434"
                        },
                        new
                        {
                            Id = 5,
                            Address = "60 Maadi, Cairo",
                            ApplicationUserId = "user-pat5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Karim Youssef",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765435"
                        },
                        new
                        {
                            Id = 6,
                            Address = "72 New Cairo, Cairo",
                            ApplicationUserId = "user-pat6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mona Ahmed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765436"
                        },
                        new
                        {
                            Id = 7,
                            Address = "85 6th October City, Giza",
                            ApplicationUserId = "user-pat7",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ali Ibrahim",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765437"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountPaid");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaymentMethod");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaymentStatus");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_Payments_PaymentDate");

                    b.HasIndex("PaymentMethod")
                        .HasDatabaseName("IX_Payments_PaymentMethod");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("IX_Payments_PaymentStatus");

                    b.HasIndex("PaymentDate", "PaymentMethod")
                        .HasDatabaseName("IX_Payments_Date_Method");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_AmountPaid_Positive", "[AmountPaid] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "Paid in full",
                            AmountPaid = 350.00m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "Visa card payment",
                            AmountPaid = 250.00m,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "Insurance coverage",
                            AmountPaid = 400.00m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "InstaPay",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "Failed transfer",
                            AmountPaid = 200.00m,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentStatus = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "Cash payment",
                            AmountPaid = 300.00m,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "Pending payment",
                            AmountPaid = 180.00m,
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentStatus = "Pending"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Dosage");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Frequency");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordId");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MedicationName");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SpecialInstructions");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Prescriptions_CreatedAt");

                    b.HasIndex("MedicalRecordId")
                        .HasDatabaseName("IX_Prescriptions_MedicalRecordId");

                    b.HasIndex("MedicationName")
                        .HasDatabaseName("IX_Prescriptions_MedicationName");

                    b.ToTable("Prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prescriptions_EndDate_After_StartDate", "[EndDate] > [StartDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Lisinopril",
                            SpecialInstructions = "يؤخذ صباحاً قبل الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "81mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Aspirin",
                            SpecialInstructions = "يؤخذ بعد الطعام",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Amoxicillin",
                            SpecialInstructions = "يؤخذ كل 8 ساعات بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10ml",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Cough Syrup",
                            SpecialInstructions = "عند الكحة الشديدة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "400mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Ibuprofen",
                            SpecialInstructions = "يؤخذ بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1500mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Glucosamine",
                            SpecialInstructions = "يؤخذ مع الوجبة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1%",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Hydrocortisone Cream",
                            SpecialInstructions = "يوضع على المنطقة المصابة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Cetirizine",
                            SpecialInstructions = "يؤخذ مساءً",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "50mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "عند بداية الصداع",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Sumatriptan",
                            SpecialInstructions = "لا يزيد عن جرعتين في اليوم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "40mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Propranolol",
                            SpecialInstructions = "للوقاية من نوبات الصداع",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "كل 6 ساعات عند الحاجة",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Paracetamol",
                            SpecialInstructions = "لخفض الحرارة وتسكين الألم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1000mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Vitamin C",
                            SpecialInstructions = "يؤخذ مع الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Clinic_System.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57b0ec93-b945-4600-b3a6-c3eda50325ff",
                            Email = "admin@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CLINIC.COM",
                            NormalizedUserName = "ADMIN@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDaGkrwgMUaewFoCLkctXqWGEMhik9rw4QxJ6S5uVXlLw7r0lyHORpCBkFLMT4bFdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "26d3cfac-7bad-4234-9fb9-675cc0503e70",
                            TwoFactorEnabled = false,
                            UserName = "admin@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c8bf8cd-d1b3-4511-992e-82fcb44f1a89",
                            Email = "dr.ahmed@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.AHMED@CLINIC.COM",
                            NormalizedUserName = "DR.AHMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHEOOjdczSQm66fPvTnsh1YUqlOJykZc3wRAGeCIlSd0eVR2pZ/cSMo6miiq/2L51A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ffab16d-03c5-40aa-82e3-c0c46f64137d",
                            TwoFactorEnabled = false,
                            UserName = "dr.ahmed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "08b89fa7-9e91-4ea8-b514-7b1fce95d19e",
                            Email = "dr.sara@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.SARA@CLINIC.COM",
                            NormalizedUserName = "DR.SARA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENDQImACiTTDrg4p2LBcJmN04IWeP54pMtc6jTNztricuTDZ20FEO0r+SzG0buksKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3edaca3-e5d7-4610-853a-430115ba0e5c",
                            TwoFactorEnabled = false,
                            UserName = "dr.sara@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b29c7229-72ff-46bb-a314-e87641ea6caa",
                            Email = "dr.mohamed@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.MOHAMED@CLINIC.COM",
                            NormalizedUserName = "DR.MOHAMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN4wwQlL/3uYjFQ1BsKzObUCOHZKwE4QblORwjFa4jJe2dEqTIj8WcKZd4DCGaev7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1f7dd68-d1f5-421e-81c5-f0d0e46d6d32",
                            TwoFactorEnabled = false,
                            UserName = "dr.mohamed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b35febc-1306-4e1a-a555-4f42835fe0d0",
                            Email = "dr.layla@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.LAYLA@CLINIC.COM",
                            NormalizedUserName = "DR.LAYLA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDTIgD5/Ot/j6MwYyzkFX/ww0YuHc2Q4/IaaHlASPk3rL9iSnLa0pf6638StIHRzlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c90a1e2e-e8a9-47b9-8f5d-1e4c066a05e9",
                            TwoFactorEnabled = false,
                            UserName = "dr.layla@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9db808e1-df22-4337-927f-512e87aa4379",
                            Email = "dr.omar@clinic.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.OMAR@CLINIC.COM",
                            NormalizedUserName = "DR.OMAR@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClv+V7cDZnPUwwfHlJxkEu+njwU7Jr2xKYJMxkhFwp2otBFOapiasTNaca81ZHkbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c862f258-8a56-4602-939f-fca51ad61040",
                            TwoFactorEnabled = false,
                            UserName = "dr.omar@clinic.com"
                        },
                        new
                        {
                            Id = "user-pat1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7365bd8e-a05f-4c46-bc53-32d42c5c0f00",
                            Email = "mahmoud.ali@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAHMOUD.ALI@GMAIL.COM",
                            NormalizedUserName = "MAHMOUD.ALI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOE608b07nU1cS8IcxrGUtX70K0hxVIBBl9eysxffmSuKh/ivCjJ8KE4nWAy9TR9Zg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "16fbbc58-00a4-4ea3-9626-199b0dcaa425",
                            TwoFactorEnabled = false,
                            UserName = "mahmoud.ali@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "472b92bf-8cf6-47a4-8556-927fb67f36a8",
                            Email = "fatima.hassan@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FATIMA.HASSAN@GMAIL.COM",
                            NormalizedUserName = "FATIMA.HASSAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEON8Jt6xEwpbtIcWElFzOzKELBZ/6K7xjMmOTqx42MsN2zUGbJzEQJoTKem0KkC2Ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02619588-9b4f-426c-b6a8-fa68b2954dd6",
                            TwoFactorEnabled = false,
                            UserName = "fatima.hassan@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d1c5d36-606a-462b-bdda-795c82adea92",
                            Email = "omar.khalid@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.KHALID@GMAIL.COM",
                            NormalizedUserName = "OMAR.KHALID@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEqR78CF6T3nXob1oWq9VF1x9UlEa4adfmtGkVMBx6Wh0mYveO9RkIG7Xyc2nHDJOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "73b63957-f453-47e5-9e41-61bc2803d0f9",
                            TwoFactorEnabled = false,
                            UserName = "omar.khalid@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f425f9d-ef02-4d93-a1f4-d7b1299c2009",
                            Email = "nour.mohamed@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NOUR.MOHAMED@GMAIL.COM",
                            NormalizedUserName = "NOUR.MOHAMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKzVz92Bt229TodGcgtBc0XySktU4UbfU2c+4ZRca7v2GGPuiodxLUmdRrqd1TwFHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1974114a-2bc5-47ca-8dbc-3a58136dc86f",
                            TwoFactorEnabled = false,
                            UserName = "nour.mohamed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd311e45-a81e-46d7-86d0-71f9d6cd3e29",
                            Email = "karim.youssef@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KARIM.YOUSSEF@GMAIL.COM",
                            NormalizedUserName = "KARIM.YOUSSEF@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClmBuu/ul0EvTJWvTdQwCR+f0USJdIT/eBINdGELfWIrD73GRCtOqJA1lrCXDAtSA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "860a041a-91d6-4997-96e2-b9794b9362ae",
                            TwoFactorEnabled = false,
                            UserName = "karim.youssef@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85202e4c-98d5-4f58-8f29-da1b32803be5",
                            Email = "mona.ahmed@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONA.AHMED@GMAIL.COM",
                            NormalizedUserName = "MONA.AHMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKFb7SBDCEkNKXCba19Pi2WzN6VjyPbk2xkWygAg8aH3H53zMg4WX1Z2wmUf2e1e0g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6aacf5a7-fd98-4cf8-a30b-22075483c896",
                            TwoFactorEnabled = false,
                            UserName = "mona.ahmed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c40dbdae-988b-40f3-a2b6-88914defd943",
                            Email = "ali.ibrahim@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.IBRAHIM@GMAIL.COM",
                            NormalizedUserName = "ALI.IBRAHIM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHLPTUjW5/TfOH8LbDoJSwSdMwSYJnSHAh6AqqIOijwoqAe5wF2Z0bBiuzOV0C42HQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5abf1b6d-eb38-4d4e-b86a-18de023cbb02",
                            TwoFactorEnabled = false,
                            UserName = "ali.ibrahim@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "22444086-99db-403f-b007-0d41c3b9c577",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-doctor",
                            ConcurrencyStamp = "2b753f14-46eb-4036-9ff7-33a638c36866",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "0add5e7d-4dcb-40f1-b4b8-da22e8a90846",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "user-doc1",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc2",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc3",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc4",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc5",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-pat1",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat2",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat3",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat4",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat5",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat6",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat7",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointment", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_System.Core.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("Doctor")
                        .HasForeignKey("Clinic_System.Core.Entities.Doctor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Clinic_System.Core.Entities.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patient", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("Patient")
                        .HasForeignKey("Clinic_System.Core.Entities.Patient", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Payment", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("Clinic_System.Core.Entities.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Prescription", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic_System.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
