// <auto-generated />
using System;
using Clinic_System.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic_System.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AppointmentDateTime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AppointmentStatus");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate")
                        .HasDatabaseName("IX_Appointments_AppointmentDate");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Appointments_CreatedAt");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Appointments_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointments_Status");

                    b.HasIndex("AppointmentDate", "Status")
                        .HasDatabaseName("IX_Appointments_Date_Status");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("IX_Appointments_Doctor_Date");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DoctorName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specialization");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Doctors_ApplicationUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Doctors_CreatedAt");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("IX_Doctors_Specialization");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Nile Street, Cairo",
                            ApplicationUserId = "user-doc1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmed Mohamed",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345671",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Address = "28 Mohandessin, Giza",
                            ApplicationUserId = "user-doc2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sara Ali",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201012345672",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Address = "42 Nasr City, Cairo",
                            ApplicationUserId = "user-doc3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mohamed Hassan",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345673",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 4,
                            Address = "88 Zamalek, Cairo",
                            ApplicationUserId = "user-doc4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1982, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Layla Ibrahim",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201012345674",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 5,
                            Address = "55 Heliopolis, Cairo",
                            ApplicationUserId = "user-doc5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khaled",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201012345675",
                            Specialization = "Neurology"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DescriptionOfTheVisit")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("VisitDescription");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Diagnosis");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_MedicalRecords_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MedicalRecords_CreatedAt");

                    b.ToTable("MedicalRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "ينصح بتقليل الملح وممارسة الرياضة بانتظام",
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "المريض يعاني من ارتفاع في ضغط الدم، تم قياس الضغط وكان 150/95",
                            Diagnosis = "Hypertension",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "الراحة والإكثار من السوائل الدافئة",
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفل يعاني من كحة شديدة وحرارة، تم الفحص السريري",
                            Diagnosis = "Acute Bronchitis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "العلاج الطبيعي مرتين أسبوعياً وتجنب حمل الأثقال",
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "ألم في الركبة اليمنى، تم عمل أشعة وظهر احتكاك بسيط",
                            Diagnosis = "Knee Osteoarthritis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "تجنب الصابون القوي واستخدام المرطبات",
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفح جلدي في اليدين والرقبة، حكة شديدة",
                            Diagnosis = "Eczema",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "تجنب المحفزات مثل القهوة والتوتر",
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "صداع نصفي متكرر مع حساسية للضوء والصوت",
                            Diagnosis = "Migraine",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "الراحة وشرب السوائل الساخنة",
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "رشح وعطس واحتقان في الأنف منذ يومين",
                            Diagnosis = "Common Cold",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PatientName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_ApplicationUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Patients_CreatedAt");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Garden City, Cairo",
                            ApplicationUserId = "user-pat1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mahmoud Ali",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765431"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Dokki, Giza",
                            ApplicationUserId = "user-pat2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fatima Hassan",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "35 Zamalek, Cairo",
                            ApplicationUserId = "user-pat3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khalid",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765433"
                        },
                        new
                        {
                            Id = 4,
                            Address = "48 Agouza, Giza",
                            ApplicationUserId = "user-pat4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nour Mohamed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765434"
                        },
                        new
                        {
                            Id = 5,
                            Address = "60 Maadi, Cairo",
                            ApplicationUserId = "user-pat5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Karim Youssef",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765435"
                        },
                        new
                        {
                            Id = 6,
                            Address = "72 New Cairo, Cairo",
                            ApplicationUserId = "user-pat6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mona Ahmed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765436"
                        },
                        new
                        {
                            Id = 7,
                            Address = "85 6th October City, Giza",
                            ApplicationUserId = "user-pat7",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ali Ibrahim",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765437"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountPaid");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaymentMethod");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_Payments_PaymentDate");

                    b.HasIndex("PaymentMethod")
                        .HasDatabaseName("IX_Payments_PaymentMethod");

                    b.HasIndex("PaymentDate", "PaymentMethod")
                        .HasDatabaseName("IX_Payments_Date_Method");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_AmountPaid_Positive", "[AmountPaid] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "Paid in full",
                            AmountPaid = 350.00m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "Visa card payment",
                            AmountPaid = 250.00m,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "Insurance coverage",
                            AmountPaid = 400.00m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Insurance"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "InstaPay transfer",
                            AmountPaid = 200.00m,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "InstaPay"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "Cash payment",
                            AmountPaid = 300.00m,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "Mastercard payment",
                            AmountPaid = 180.00m,
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard"
                        });
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Prescriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Dosage");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Frequency");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordId");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MedicationName");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SpecialInstructions");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Prescriptions_CreatedAt");

                    b.HasIndex("MedicalRecordId")
                        .HasDatabaseName("IX_Prescriptions_MedicalRecordId");

                    b.HasIndex("MedicationName")
                        .HasDatabaseName("IX_Prescriptions_MedicationName");

                    b.ToTable("Prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prescriptions_EndDate_After_StartDate", "[EndDate] > [StartDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Lisinopril",
                            SpecialInstructions = "يؤخذ صباحاً قبل الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "81mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Aspirin",
                            SpecialInstructions = "يؤخذ بعد الطعام",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Amoxicillin",
                            SpecialInstructions = "يؤخذ كل 8 ساعات بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10ml",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Cough Syrup",
                            SpecialInstructions = "عند الكحة الشديدة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "400mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Ibuprofen",
                            SpecialInstructions = "يؤخذ بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1500mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Glucosamine",
                            SpecialInstructions = "يؤخذ مع الوجبة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1%",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Hydrocortisone Cream",
                            SpecialInstructions = "يوضع على المنطقة المصابة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Cetirizine",
                            SpecialInstructions = "يؤخذ مساءً",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "50mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "عند بداية الصداع",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Sumatriptan",
                            SpecialInstructions = "لا يزيد عن جرعتين في اليوم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "40mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Propranolol",
                            SpecialInstructions = "للوقاية من نوبات الصداع",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "كل 6 ساعات عند الحاجة",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Paracetamol",
                            SpecialInstructions = "لخفض الحرارة وتسكين الألم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1000mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Vitamin C",
                            SpecialInstructions = "يؤخذ مع الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Clinic_System.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03a669e0-9360-4eb4-a600-5d1d8e4b8408",
                            Email = "admin@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CLINIC.COM",
                            NormalizedUserName = "ADMIN@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIguLIMO1T7IkS3rKPvq/q7dF/ym5Op2DJGa4kX7rSipfxjUwEAYxlDFhiPHDyhmqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "102923b1-257d-40f5-8587-88efd3a0a546",
                            TwoFactorEnabled = false,
                            UserName = "admin@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6ca5b81-74ac-42dc-a0f6-713f2b76b2f1",
                            Email = "dr.ahmed@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.AHMED@CLINIC.COM",
                            NormalizedUserName = "DR.AHMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELkz0slYrYJ8f7R9j6Z2UBuGUe3gDETgOKBR9QhHoIlakZklnlqscDmiEOm8hJZLHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b44544e-7b7e-4d12-898a-d0fc740d0683",
                            TwoFactorEnabled = false,
                            UserName = "dr.ahmed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0eaf01c8-8789-49bc-85ec-fcf548e78bc0",
                            Email = "dr.sara@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.SARA@CLINIC.COM",
                            NormalizedUserName = "DR.SARA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECY1251lLAFW//+p064R4dN9TcWr+E0HA/Kn/qQ5C606k+m0ypCLT/VaKal6hKd7Jw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80c1f858-a53d-4c4f-a98c-7452e2761597",
                            TwoFactorEnabled = false,
                            UserName = "dr.sara@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49ba24af-e01e-4deb-bc88-e9787e232d12",
                            Email = "dr.mohamed@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.MOHAMED@CLINIC.COM",
                            NormalizedUserName = "DR.MOHAMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKNJ9EgxqCQMu+0D7k9FwdhU6lnwb7hLC3IWQKKPZ8PgqkVQ0mS38uGxds/UDiMF/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6bcd168f-455b-46f2-8ce1-5f113cec1b83",
                            TwoFactorEnabled = false,
                            UserName = "dr.mohamed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52a4f570-3610-4ef6-b458-1542785cf19d",
                            Email = "dr.layla@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.LAYLA@CLINIC.COM",
                            NormalizedUserName = "DR.LAYLA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMlstXAIwwuLZZZIBWLN9XKHByF70/wa02Cri+W04Nm4pbD/rr3u//5faYpws6USvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a373905-1846-4989-a736-990643a00f79",
                            TwoFactorEnabled = false,
                            UserName = "dr.layla@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98e8b64b-8398-4ee3-9dc8-572efd9bb0d4",
                            Email = "dr.omar@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.OMAR@CLINIC.COM",
                            NormalizedUserName = "DR.OMAR@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMenjJdnFjONiY2PBm3XSyinThLVQdoCQkUie0ohkC9Cn8tBxfOzb3rt8n4ZCdBvVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7a71207-7907-4ff1-b387-b0c2c7899c64",
                            TwoFactorEnabled = false,
                            UserName = "dr.omar@clinic.com"
                        },
                        new
                        {
                            Id = "user-pat1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8bad088a-fbad-4064-8983-cdff77e3b490",
                            Email = "mahmoud.ali@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAHMOUD.ALI@GMAIL.COM",
                            NormalizedUserName = "MAHMOUD.ALI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH6X1xd8xzgBfJUsVoVHiiwbrMTwm6R6EAYgwKntvPPORSU+uYDdND+DYBAPK2KvFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6586afed-428f-47fc-8b82-c06f55ad1597",
                            TwoFactorEnabled = false,
                            UserName = "mahmoud.ali@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e96ea37-46a3-45ed-a8ca-cfc772b63044",
                            Email = "fatima.hassan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FATIMA.HASSAN@GMAIL.COM",
                            NormalizedUserName = "FATIMA.HASSAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFABX9byKyc+aXKlk878Ff/DaOnaBW7IGkkX24ObwdcN7eW+L9lYLB2ij21LI+oa8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d556c03-3430-4ca2-a661-0c7b40bd6ab8",
                            TwoFactorEnabled = false,
                            UserName = "fatima.hassan@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7da4e5a0-71e5-43f0-8e1b-582c23a4feab",
                            Email = "omar.khalid@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.KHALID@GMAIL.COM",
                            NormalizedUserName = "OMAR.KHALID@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFFvvGe0kP+40HnNLIFe4VLExZD6zCRM2ee2gu0zUwNeVD6NjbuqUbMJnVmbkszROg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62fae885-e700-4186-8c6b-a319394ac402",
                            TwoFactorEnabled = false,
                            UserName = "omar.khalid@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41a7ed24-55fb-4fa5-8769-d3813d6f38c0",
                            Email = "nour.mohamed@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NOUR.MOHAMED@GMAIL.COM",
                            NormalizedUserName = "NOUR.MOHAMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMgb5bg+z00kg7Ot8nTWWlMG1uJMMdJVfuPvEnzHX/M1DvEPk4lo3MKIInwKcZJC3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1ba4f59-4b9a-4b89-998f-a5ac8c5727de",
                            TwoFactorEnabled = false,
                            UserName = "nour.mohamed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2acdec06-b7e8-4358-952a-bb3e8f321a00",
                            Email = "karim.youssef@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KARIM.YOUSSEF@GMAIL.COM",
                            NormalizedUserName = "KARIM.YOUSSEF@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIIJF6fqqIDRxcqtPpEU0XDCCfyalYzCzfUZ/OylD6UmY/qwvwcUT2/M4RoYTrKmlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b23bb556-34e7-4817-bafe-6096d2c1a19a",
                            TwoFactorEnabled = false,
                            UserName = "karim.youssef@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "567a44c3-5482-4373-85f9-546ed1f0b715",
                            Email = "mona.ahmed@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONA.AHMED@GMAIL.COM",
                            NormalizedUserName = "MONA.AHMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJznXQIcZ4aFhXkHRTRIzOH5f02AKpgNaZGPuDHX9tuORs6iBld/Df2HmuBU5nIm9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "44c7394f-b058-434d-a6c9-3a4c78dfe8c0",
                            TwoFactorEnabled = false,
                            UserName = "mona.ahmed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9d03799a-bbe9-4e8f-a260-098b53855e9d",
                            Email = "ali.ibrahim@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.IBRAHIM@GMAIL.COM",
                            NormalizedUserName = "ALI.IBRAHIM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJwSxEtcPE4DvJDXjbGpsR7kcD8QLkFCX80kzHvTIR5NuAqff0KM/XxWKnyzwOSQ3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "984c64a0-2c97-4ead-94e9-2899c7fcf142",
                            TwoFactorEnabled = false,
                            UserName = "ali.ibrahim@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "1a3e836c-c707-483d-900a-a2b4ffe54406",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-doctor",
                            ConcurrencyStamp = "51e3a6db-c70a-4465-b461-c828281153ac",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "5649fdc8-cc0e-4f45-a98f-4aeb75c9cd56",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "user-doc1",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc2",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc3",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc4",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc5",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-pat1",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat2",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat3",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat4",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat5",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat6",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat7",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointments", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Doctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_System.Core.Entities.Patients", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctors", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("Doctor")
                        .HasForeignKey("Clinic_System.Core.Entities.Doctors", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecords", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Appointments", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Clinic_System.Core.Entities.MedicalRecords", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patients", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("Patient")
                        .HasForeignKey("Clinic_System.Core.Entities.Patients", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Payments", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.Appointments", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("Clinic_System.Core.Entities.Payments", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Prescriptions", b =>
                {
                    b.HasOne("Clinic_System.Core.Entities.MedicalRecords", "MedicalRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clinic_System.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Appointments", b =>
                {
                    b.Navigation("MedicalRecord");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Doctors", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.MedicalRecords", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Clinic_System.Core.Entities.Patients", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic_System.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
