// <auto-generated />
using System;
using Clinic_System.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125002349_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic_System.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27ce55d2-9bd4-4292-89aa-2ff20cc0318b",
                            Email = "admin@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CLINIC.COM",
                            NormalizedUserName = "ADMIN@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELvCwoVWZpSOpiM0PBhIuCb05AcDUMARgcH3M7VIfFZ1R7IJ98jE6JuBPALje5+Kow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "16e0ce06-63b3-4b73-a228-04d1d6d13d6a",
                            TwoFactorEnabled = false,
                            UserName = "admin@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24a99b5e-6e3e-4ab1-a674-2e98c15ac576",
                            Email = "dr.ahmed@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.AHMED@CLINIC.COM",
                            NormalizedUserName = "DR.AHMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFTBKTLlO8Evbjck+EMsxXtwe+lhnXM2Eyj7K+2FxAw7aGc06slGZQzCehc/e5rn/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c2e156a1-c264-45dd-9ff3-b458e7c3399c",
                            TwoFactorEnabled = false,
                            UserName = "dr.ahmed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c5bc0f9-ecd2-43aa-810c-17e79e9b1148",
                            Email = "dr.sara@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.SARA@CLINIC.COM",
                            NormalizedUserName = "DR.SARA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENKl0LZSW54BJaXHlPcjnbKOnwxnC3x2N0LeM9iTZNx4sAsTDuG9Yn2XEhntUDrWvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b5e0889f-314f-43b8-b777-0e2b02e66d21",
                            TwoFactorEnabled = false,
                            UserName = "dr.sara@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7755a86b-bf57-4d42-942a-1ebfdbd4741f",
                            Email = "dr.mohamed@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.MOHAMED@CLINIC.COM",
                            NormalizedUserName = "DR.MOHAMED@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPprMITE4FRmyetQD9nAL7BSR9FyPZwE017YwcrilT17aN70e0FGii8UKeLJyYBoSA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31742e2b-5d30-4a4a-b96f-0d337c43410f",
                            TwoFactorEnabled = false,
                            UserName = "dr.mohamed@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edbdd483-c5a0-46ec-a0c4-d567c4e4e6bc",
                            Email = "dr.layla@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.LAYLA@CLINIC.COM",
                            NormalizedUserName = "DR.LAYLA@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH0FVk93L13TSzoUDlte0UR6pP821DYosA4p37n8W8qc5tRyXeyBq3s32JD0rfKjgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fd8e05f3-8537-4227-99de-0439a0ce04f9",
                            TwoFactorEnabled = false,
                            UserName = "dr.layla@clinic.com"
                        },
                        new
                        {
                            Id = "user-doc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d63b76a-2c87-478d-8959-2aeab599bbd2",
                            Email = "dr.omar@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.OMAR@CLINIC.COM",
                            NormalizedUserName = "DR.OMAR@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgrwOZLiE2jBftJT0IWyiUyzRLfXUuqNQazsvelJ484KFN/1qp9qeN8IJCeKcL3TA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db6adf20-58ba-44f3-872a-3cd37ab3fc11",
                            TwoFactorEnabled = false,
                            UserName = "dr.omar@clinic.com"
                        },
                        new
                        {
                            Id = "user-pat1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76e88d86-8eec-4cff-8ef3-40ca817c7923",
                            Email = "mahmoud.ali@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAHMOUD.ALI@GMAIL.COM",
                            NormalizedUserName = "MAHMOUD.ALI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOzRtnzegIxSDrQN+5Akh9A/nWsgAffiaD6iIhvZqMbWvcivG2BYaplM0BnWTvvgKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "523cd1f8-fff9-475d-91c0-de3e43e12e07",
                            TwoFactorEnabled = false,
                            UserName = "mahmoud.ali@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ffc9c485-6775-40aa-aae4-253ec6391d3b",
                            Email = "fatima.hassan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FATIMA.HASSAN@GMAIL.COM",
                            NormalizedUserName = "FATIMA.HASSAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDQ6h48Tejay9g0UO++UxwYpAsabaT2+0qUOfr0WgJUlBh7Y31a7uUv6HirIvttyOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2820a7f9-d6fe-4b3d-9392-2eea767fa756",
                            TwoFactorEnabled = false,
                            UserName = "fatima.hassan@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "84e13bfc-c071-437a-95f6-01897a3bc89a",
                            Email = "omar.khalid@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.KHALID@GMAIL.COM",
                            NormalizedUserName = "OMAR.KHALID@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEA4LlISmYjj8owIAQYbmCtJTefTHzpl3AEYbsEkR5ytt4+TqB5MpgnaCgqYsCHyag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b0880d1d-fd88-4251-a591-ba19cecc1380",
                            TwoFactorEnabled = false,
                            UserName = "omar.khalid@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da0eccfa-271e-418f-8249-b2f7e02c4af2",
                            Email = "nour.mohamed@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NOUR.MOHAMED@GMAIL.COM",
                            NormalizedUserName = "NOUR.MOHAMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMBC6oy3uQwvrJDpUoBDETCDL9CoJhfAgWbMoPBKnQUNQ0qU+/4RbRQm4j7KLPW2EA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ffebb7c-a023-4352-9a39-f4563b42a7c7",
                            TwoFactorEnabled = false,
                            UserName = "nour.mohamed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ca6440a-4594-4e89-b422-b98a1523e10b",
                            Email = "karim.youssef@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KARIM.YOUSSEF@GMAIL.COM",
                            NormalizedUserName = "KARIM.YOUSSEF@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEvsDW0AdzJ2IaGqUORZuvuMC30/mUuf+JLTTZq2IAnzrQAElm1HqAhd2QlUFQ155w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e4613b4-bcd5-460d-b9e8-7ba54509b8be",
                            TwoFactorEnabled = false,
                            UserName = "karim.youssef@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb4e0d81-aa82-45a1-8fd8-f4fd612edd9e",
                            Email = "mona.ahmed@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONA.AHMED@GMAIL.COM",
                            NormalizedUserName = "MONA.AHMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE1SCvyK/y5q/4GNdu+Bsmfw56gCLWlX30v3gThaF9RSe67nvZc5icC0pPIY4UXfCg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d4de0fba-4282-4053-848a-1c3d58b066e7",
                            TwoFactorEnabled = false,
                            UserName = "mona.ahmed@gmail.com"
                        },
                        new
                        {
                            Id = "user-pat7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d37c037e-5130-466f-ba13-3bd02524a7b1",
                            Email = "ali.ibrahim@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.IBRAHIM@GMAIL.COM",
                            NormalizedUserName = "ALI.IBRAHIM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPCxJ8bEBrWQR/+h+JCGLKiwJXEBPQaD8aIw16htKpqZf5s/zJLVVHX7hKFC1ZDelQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "919a380f-8d2c-4aba-b923-01c53ab85231",
                            TwoFactorEnabled = false,
                            UserName = "ali.ibrahim@gmail.com"
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.Appointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AppointmentDateTime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AppointmentStatus");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate")
                        .HasDatabaseName("IX_Appointments_AppointmentDate");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Appointments_CreatedAt");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Appointments_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointments_Status");

                    b.HasIndex("AppointmentDate", "Status")
                        .HasDatabaseName("IX_Appointments_Date_Status");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("IX_Appointments_Doctor_Date");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            PatientId = 3,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            PatientId = 4,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            PatientId = 5,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 6,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.Doctors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DoctorName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specialization");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Doctors_CreatedAt");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("IX_Doctors_Specialization");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Nile Street, Cairo",
                            ApplicationUserId = "user-doc1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmed Mohamed",
                            Gender = 1,
                            IsDeleted = false,
                            Phone = "+201012345671",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Address = "28 Mohandessin, Giza",
                            ApplicationUserId = "user-doc2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sara Ali",
                            Gender = 2,
                            IsDeleted = false,
                            Phone = "+201012345672",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Address = "42 Nasr City, Cairo",
                            ApplicationUserId = "user-doc3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mohamed Hassan",
                            Gender = 1,
                            IsDeleted = false,
                            Phone = "+201012345673",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 4,
                            Address = "88 Zamalek, Cairo",
                            ApplicationUserId = "user-doc4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1982, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Layla Ibrahim",
                            Gender = 2,
                            IsDeleted = false,
                            Phone = "+201012345674",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 5,
                            Address = "55 Heliopolis, Cairo",
                            ApplicationUserId = "user-doc5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khaled",
                            Gender = 1,
                            IsDeleted = false,
                            Phone = "+201012345675",
                            Specialization = "Neurology"
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.MedicalRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DescriptionOfTheVisit")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("VisitDescription");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Diagnosis");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_MedicalRecords_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MedicalRecords_CreatedAt");

                    b.ToTable("MedicalRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "ينصح بتقليل الملح وممارسة الرياضة بانتظام",
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "المريض يعاني من ارتفاع في ضغط الدم، تم قياس الضغط وكان 150/95",
                            Diagnosis = "Hypertension",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "الراحة والإكثار من السوائل الدافئة",
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفل يعاني من كحة شديدة وحرارة، تم الفحص السريري",
                            Diagnosis = "Acute Bronchitis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "العلاج الطبيعي مرتين أسبوعياً وتجنب حمل الأثقال",
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "ألم في الركبة اليمنى، تم عمل أشعة وظهر احتكاك بسيط",
                            Diagnosis = "Knee Osteoarthritis",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "تجنب الصابون القوي واستخدام المرطبات",
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "طفح جلدي في اليدين والرقبة، حكة شديدة",
                            Diagnosis = "Eczema",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "تجنب المحفزات مثل القهوة والتوتر",
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "صداع نصفي متكرر مع حساسية للضوء والصوت",
                            Diagnosis = "Migraine",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "الراحة وشرب السوائل الساخنة",
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionOfTheVisit = "رشح وعطس واحتقان في الأنف منذ يومين",
                            Diagnosis = "Common Cold",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.Patients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PatientName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Patients_CreatedAt");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Garden City, Cairo",
                            ApplicationUserId = "user-pat1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mahmoud Ali",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765431"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Dokki, Giza",
                            ApplicationUserId = "user-pat2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fatima Hassan",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "35 Zamalek, Cairo",
                            ApplicationUserId = "user-pat3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khalid",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765433"
                        },
                        new
                        {
                            Id = 4,
                            Address = "48 Agouza, Giza",
                            ApplicationUserId = "user-pat4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nour Mohamed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765434"
                        },
                        new
                        {
                            Id = 5,
                            Address = "60 Maadi, Cairo",
                            ApplicationUserId = "user-pat5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Karim Youssef",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765435"
                        },
                        new
                        {
                            Id = 6,
                            Address = "72 New Cairo, Cairo",
                            ApplicationUserId = "user-pat6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mona Ahmed",
                            Gender = "Female",
                            IsDeleted = false,
                            Phone = "+201098765436"
                        },
                        new
                        {
                            Id = 7,
                            Address = "85 6th October City, Giza",
                            ApplicationUserId = "user-pat7",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ali Ibrahim",
                            Gender = "Male",
                            IsDeleted = false,
                            Phone = "+201098765437"
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountPaid");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaymentMethod");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_AppointmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_Payments_PaymentDate");

                    b.HasIndex("PaymentMethod")
                        .HasDatabaseName("IX_Payments_PaymentMethod");

                    b.HasIndex("PaymentDate", "PaymentMethod")
                        .HasDatabaseName("IX_Payments_Date_Method");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_AmountPaid_Positive", "[AmountPaid] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "Paid in full",
                            AmountPaid = 350.00m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "Visa card payment",
                            AmountPaid = 250.00m,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "Insurance coverage",
                            AmountPaid = 400.00m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Insurance"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "InstaPay transfer",
                            AmountPaid = 200.00m,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "InstaPay"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "Cash payment",
                            AmountPaid = 300.00m,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "Mastercard payment",
                            AmountPaid = 180.00m,
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard"
                        });
                });

            modelBuilder.Entity("Clinic_System.Model.Prescriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Dosage");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Frequency");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordId");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MedicationName");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SpecialInstructions");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Prescriptions_CreatedAt");

                    b.HasIndex("MedicalRecordId")
                        .HasDatabaseName("IX_Prescriptions_MedicalRecordId");

                    b.HasIndex("MedicationName")
                        .HasDatabaseName("IX_Prescriptions_MedicationName");

                    b.ToTable("Prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prescriptions_EndDate_After_StartDate", "[EndDate] > [StartDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Lisinopril",
                            SpecialInstructions = "يؤخذ صباحاً قبل الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "81mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 1,
                            MedicationName = "Aspirin",
                            SpecialInstructions = "يؤخذ بعد الطعام",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Amoxicillin",
                            SpecialInstructions = "يؤخذ كل 8 ساعات بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10ml",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "ثلاث مرات يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 2,
                            MedicationName = "Cough Syrup",
                            SpecialInstructions = "عند الكحة الشديدة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "400mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Ibuprofen",
                            SpecialInstructions = "يؤخذ بعد الأكل",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1500mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 3,
                            MedicationName = "Glucosamine",
                            SpecialInstructions = "يؤخذ مع الوجبة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1%",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Hydrocortisone Cream",
                            SpecialInstructions = "يوضع على المنطقة المصابة",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "10mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 4,
                            MedicationName = "Cetirizine",
                            SpecialInstructions = "يؤخذ مساءً",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "50mg",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "عند بداية الصداع",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Sumatriptan",
                            SpecialInstructions = "لا يزيد عن جرعتين في اليوم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "40mg",
                            EndDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرتين يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 5,
                            MedicationName = "Propranolol",
                            SpecialInstructions = "للوقاية من نوبات الصداع",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "كل 6 ساعات عند الحاجة",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Paracetamol",
                            SpecialInstructions = "لخفض الحرارة وتسكين الألم",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dosage = "1000mg",
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "مرة واحدة يومياً",
                            IsDeleted = false,
                            MedicalRecordId = 6,
                            MedicationName = "Vitamin C",
                            SpecialInstructions = "يؤخذ مع الإفطار",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-doctor",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-patient",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "user-doc1",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc2",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc3",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc4",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-doc5",
                            RoleId = "role-doctor"
                        },
                        new
                        {
                            UserId = "user-pat1",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat2",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat3",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat4",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat5",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat6",
                            RoleId = "role-patient"
                        },
                        new
                        {
                            UserId = "user-pat7",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic_System.Model.Appointments", b =>
                {
                    b.HasOne("Clinic_System.Model.Doctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_System.Model.Patients", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic_System.Model.Doctors", b =>
                {
                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Doctor")
                        .HasForeignKey("Clinic_System.Model.Doctors", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Clinic_System.Model.MedicalRecords", b =>
                {
                    b.HasOne("Clinic_System.Model.Appointments", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Clinic_System.Model.MedicalRecords", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Model.Patients", b =>
                {
                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Patient")
                        .HasForeignKey("Clinic_System.Model.Patients", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Clinic_System.Model.Payments", b =>
                {
                    b.HasOne("Clinic_System.Model.Appointments", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("Clinic_System.Model.Payments", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_System.Model.Prescriptions", b =>
                {
                    b.HasOne("Clinic_System.Model.MedicalRecords", "MedicalRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clinic_System.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Identity.Models.ApplicationUser", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_System.Model.Appointments", b =>
                {
                    b.Navigation("MedicalRecord");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Clinic_System.Model.Doctors", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic_System.Model.MedicalRecords", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Clinic_System.Model.Patients", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
