name: Clinic System CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore "Clinic System.API.sln"
      
    - name: Build
      run: dotnet build "Clinic System.API.sln" --no-restore
      
    - name: Test
      run: dotnet test "Clinic System.API.sln" --no-build --verbosity normal